apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
      - name: web
        image: {{ .Values.web.image }}
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: db-config
        - secretRef:
            name: db-secret
        - secretRef:
            name: cloudinary-secret

