apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"https://index.docker.io/v1/\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" .Values.dockerhub.username .Values.dockerhub.password .Values.dockerhub.email (printf "%s:%s" .Values.dockerhub.username .Values.dockerhub.password | b64enc) | b64enc }}

