apiVersion: v1
kind: Secret
metadata:
  name: cloudinary-secret
type: Opaque
stringData:
  CLOUDINARY_CLOUD_NAME: "{{ .Values.cloudinary.cloudName }}"
  CLOUDINARY_API_KEY: "{{ .Values.cloudinary.apiKey }}"
  CLOUDINARY_API_SECRET: "{{ .Values.cloudinary.apiSecret }}"

