apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.username }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password }}
  POSTGRES_DB: {{ .Values.postgres.database }}
  DB_USERNAME: {{ .Values.postgres.username }}
  DB_PASSWORD: {{ .Values.postgres.password }}
  DATABASE_URL: postgres://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@db:5432/{{ .Values.postgres.database }}

