apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  POSTGRES_DB: aW5zdGFfY2xvbmVfZGV2ZWxvcG1lbnQ=
  DB_USERNAME: cG9zdGdyZXM=
  DB_PASSWORD: cGFzc3dvcmQ=
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpwYXNzd29yZEBkYjo1NDMyL2luc3RhX2Nsb25lX2RldmVsb3BtZW50

