apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      imagePullSecrets:
       - name: dockerhub-secret

      containers:
      - name: web
        image: rafaydevsinc/insta-clone1
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
           name: db-secret
        - configMapRef:
           name: db-config
        - secretRef:
            name: cloudinary-secret




            
        # env:
        # - name: DB_HOST
        #   valueFrom:
        #     configMapKeyRef:
        #       name: db-config
        #       key: DB_HOST
        # - name: DB_USERNAME
        #   valueFrom:
        #     secretKeyRef:
        #       name: db-secret
        #       key: DB_USERNAME
        # - name: DB_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: db-secret
        #       key: DB_PASSWORD
        # - name: DATABASE_URL
        #   valueFrom:
        #     secretKeyRef:
        #       name: db-secret
        #       key: DATABASE_URL
        # - name: RAILS_MAX_THREADS
        #   valueFrom:
        #     configMapKeyRef:
        #       name: db-config
        #       key: RAILS_MAX_THREADS

        # # Cloudinary environment variables
        # - name: CLOUDINARY_CLOUD_NAME
        #   valueFrom:
        #     secretKeyRef:
        #       name: cloudinary-secret
        #       key: CLOUDINARY_CLOUD_NAME
        # - name: CLOUDINARY_API_KEY
        #   valueFrom:
        #     secretKeyRef:
        #       name: cloudinary-secret
        #       key: CLOUDINARY_API_KEY
        # - name: CLOUDINARY_API_SECRET
        #   valueFrom:
        #     secretKeyRef:
        #       name: cloudinary-secret
        #       key: CLOUDINARY_API_SECRET