{{- range .Values.services }}
{{- if .enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      imagePullSecrets:
        - name: dockerhub-secret  
      containers:
        - name: {{ .name }}
          image: {{ .image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .port }}
{{- if eq .name "web" }}
          envFrom:
            - configMapRef:
                name: db-config
            - secretRef:
                name: db-secret
            - secretRef:
                name: cloudinary-secret
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
spec:
  selector:
    app: {{ .name }}
  ports:
    - protocol: TCP
      port: {{ .port }}
      targetPort: {{ .port }}
{{- end }}
{{- end }}
